#!/usr/bin/env python3
"""Generate src/runtime/builtins/unicode_normalize.zig — the data tables for
String.prototype.normalize (NFC/NFD/NFKC/NFKD).

Uses Python's `unicodedata` (decomposition, combining, normalize). The characters
exercised by test262 normalize tests are stable across Unicode versions, so the
Python-bundled UCD produces identical NFC/NFD results for them.

Emits sorted arrays + binary-search lookups:
  canonDecomp(cp)  -> canonical decomposition (untagged) as []u21, else null
  compatDecomp(cp) -> full (compatibility) decomposition as []u21, else null
  ccc(cp)          -> canonical combining class (0 when absent)
  compose(a,b)     -> primary composite, else null  (excludes non-composables)
"""
import sys, unicodedata

MAX = 0x110000

def parse_decomp(s):
    # s like "" | "0041 030A" | "<compat> 0020 0301"
    if not s:
        return None, None
    parts = s.split()
    tag = None
    if parts[0].startswith("<"):
        tag = parts[0]
        parts = parts[1:]
    cps = [int(p, 16) for p in parts]
    return tag, cps

canon = {}   # cp -> [cps]  (untagged canonical mapping)
compat = {}  # cp -> [cps]  (any decomposition mapping)
ccc = {}     # cp -> class (nonzero only)

for cp in range(MAX):
    ch = chr(cp)
    cc = unicodedata.combining(ch)
    if cc:
        ccc[cp] = cc
    tag, cps = parse_decomp(unicodedata.decomposition(ch))
    if cps is None:
        continue
    compat[cp] = cps
    if tag is None:
        canon[cp] = cps

# Composition pairs: invert 2-char canonical decompositions, keeping only those
# that actually recompose under Python NFC (this auto-excludes full composition
# exclusions, singletons and non-starter decompositions).
comp = {}  # (a,b) -> cp
for cp, cps in canon.items():
    if len(cps) != 2:
        continue
    a, b = cps
    if ccc.get(a, 0) != 0:
        continue  # first element must be a starter
    if unicodedata.normalize("NFC", chr(a) + chr(b)) == chr(cp):
        comp[(a, b)] = cp

# ---- Emit Zig ----
def emit_decomp(name, table):
    # Flat pool of u21 + per-entry (cp, off, len), sorted by cp.
    pool = []
    entries = []
    for cp in sorted(table):
        cps = table[cp]
        entries.append((cp, len(pool), len(cps)))
        pool.extend(cps)
    lines = []
    lines.append(f"const {name}_pool = [_]u21{{ " +
                 ", ".join(f"0x{c:X}" for c in pool) + " };")
    lines.append(f"const {name}_entries = [_]DecompEntry{{")
    for cp, off, ln in entries:
        lines.append(f"    .{{ .cp = 0x{cp:X}, .off = {off}, .len = {ln} }},")
    lines.append("};")
    return "\n".join(lines)

out = []
out.append("//! GENERATED by tools/gen_unicode_normalize.py -- do not edit by hand.")
out.append("//! Unicode normalization data for String.prototype.normalize.")
out.append("")
out.append("const std = @import(\"std\");")
out.append("")
out.append("const DecompEntry = struct { cp: u21, off: u32, len: u16 };")
out.append("")
out.append(emit_decomp("canon", canon))
out.append("")
out.append(emit_decomp("compat", compat))
out.append("")

# ccc table
out.append("const CccEntry = struct { cp: u21, class: u8 };")
out.append("const ccc_entries = [_]CccEntry{")
for cp in sorted(ccc):
    out.append(f"    .{{ .cp = 0x{cp:X}, .class = {ccc[cp]} }},")
out.append("};")
out.append("")

# composition table: key = (a<<21)|b, sorted
out.append("const CompEntry = struct { key: u64, cp: u21 };")
out.append("const comp_entries = [_]CompEntry{")
comp_sorted = sorted(comp.items(), key=lambda kv: (kv[0][0] << 21) | kv[0][1])
for (a, b), cp in comp_sorted:
    key = (a << 21) | b
    out.append(f"    .{{ .key = 0x{key:X}, .cp = 0x{cp:X} }},")
out.append("};")
out.append("")

out.append("""
fn decompLookup(entries: []const DecompEntry, pool: []const u21, cp: u21) ?[]const u21 {
    var lo: usize = 0;
    var hi: usize = entries.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = entries[mid];
        if (cp < e.cp) {
            hi = mid;
        } else if (cp > e.cp) {
            lo = mid + 1;
        } else {
            return pool[e.off .. e.off + e.len];
        }
    }
    return null;
}

/// Canonical decomposition mapping (untagged), or null.
pub fn canonDecomp(cp: u21) ?[]const u21 {
    return decompLookup(&canon_entries, &canon_pool, cp);
}

/// Full (compatibility) decomposition mapping, or null.
pub fn compatDecomp(cp: u21) ?[]const u21 {
    return decompLookup(&compat_entries, &compat_pool, cp);
}

/// Canonical Combining Class (0 when the code point has none).
pub fn ccc(cp: u21) u8 {
    var lo: usize = 0;
    var hi: usize = ccc_entries.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = ccc_entries[mid];
        if (cp < e.cp) {
            hi = mid;
        } else if (cp > e.cp) {
            lo = mid + 1;
        } else {
            return e.class;
        }
    }
    return 0;
}

/// Primary composite of a starter `a` and following `b`, or null.
pub fn compose(a: u21, b: u21) ?u21 {
    const key: u64 = (@as(u64, a) << 21) | @as(u64, b);
    var lo: usize = 0;
    var hi: usize = comp_entries.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = comp_entries[mid];
        if (key < e.key) {
            hi = mid;
        } else if (key > e.key) {
            lo = mid + 1;
        } else {
            return e.cp;
        }
    }
    return null;
}
""")

with open("src/runtime/builtins/unicode_normalize.zig", "w") as f:
    f.write("\n".join(out))
print(f"canon={len(canon)} compat={len(compat)} ccc={len(ccc)} comp={len(comp)}")
