#!/usr/bin/env python3
"""Generate src/runtime/builtins/unicode_prop_tables.zig from the test262
generated RegExp property-escapes tests (Unicode v17.0.0).

Each generated (non-negated) test file embeds `matchSymbols`, the exact set of
code points that a property's `\\p{...}` escape must match. We parse those and
emit sorted, disjoint [lo,hi] range tables plus an exact-spelling lookup.

Property names in JS regex property escapes are matched EXACTLY against a fixed
list of canonical names + aliases (no case/whitespace loosening). The test262
generator emits every valid spelling, so every spelling we harvest here is
exactly the set that must be accepted; anything absent must be a SyntaxError.
"""
import os, re, sys

GEN_DIR = "external/test262/test/built-ins/RegExp/property-escapes/generated"
OUT = "src/runtime/builtins/unicode_prop_tables.zig"

hexnum = re.compile(r"0x([0-9A-Fa-f]+)")

def parse_buildstrings(text):
    """Return dict var_name -> sorted disjoint list of (lo,hi) ranges."""
    out = {}
    # const VAR = buildString({ ... });  (non-greedy up to the matching });)
    for m in re.finditer(r"const\s+(\w+)\s*=\s*buildString\(\{(.*?)\}\);", text, re.S):
        var = m.group(1)
        body = m.group(2)
        # loneCodePoints: [ ... ]  and  ranges: [ ... ]
        lone = []
        ranges = []
        lm = re.search(r"loneCodePoints\s*:\s*\[(.*?)\]", body, re.S)
        if lm:
            lone = [int(x, 16) for x in hexnum.findall(lm.group(1))]
        rm = re.search(r"ranges\s*:\s*\[(.*?\])\s*\]\s*$", body, re.S)
        # ranges is a list of [lo,hi]; grab all pairs
        if rm is None:
            rm = re.search(r"ranges\s*:\s*\[(.*)\]", body, re.S)
        pairs = []
        if rm:
            for pm in re.finditer(r"\[\s*0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)\s*\]", rm.group(1)):
                pairs.append((int(pm.group(1), 16), int(pm.group(2), 16)))
        allr = [(c, c) for c in lone] + pairs
        out[var] = merge(allr)
    return out

def merge(ranges):
    if not ranges:
        return []
    ranges = sorted(ranges)
    out = [list(ranges[0])]
    for lo, hi in ranges[1:]:
        if lo <= out[-1][1] + 1:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return [(a, b) for a, b in out]

def parse_mappings(text, vars_):
    """Return list of (spelling, var) for every lowercase \\p{...} occurrence,
    where var is the buildString variable passed to testPropertyEscapes."""
    res = []
    for m in re.finditer(
        r"testPropertyEscapes\(\s*/\^\\([pP])\{(.*?)\}\+\$/u\s*,\s*(\w+)", text, re.S
    ):
        pP, spelling, var = m.group(1), m.group(2), m.group(3)
        if pP != "p":
            continue  # only positive escapes map directly to their set
        if var not in vars_:
            continue
        res.append((spelling, var))
    return res

def main():
    files = sorted(f for f in os.listdir(GEN_DIR)
                   if f.endswith(".js") and not f.endswith("-negated.js"))
    spelling_to_set = {}   # spelling -> tuple of ranges
    for fn in files:
        with open(os.path.join(GEN_DIR, fn), encoding="utf-8") as fh:
            text = fh.read()
        vars_ = parse_buildstrings(text)
        for spelling, var in parse_mappings(text, vars_):
            rng = tuple(vars_[var])
            if spelling in spelling_to_set and spelling_to_set[spelling] != rng:
                print(f"WARN: conflicting set for {spelling!r} in {fn}", file=sys.stderr)
            spelling_to_set[spelling] = rng

    # Dedupe identical range sets -> shared table constant.
    unique = {}   # rangetuple -> index
    order = []
    for rng in spelling_to_set.values():
        if rng not in unique:
            unique[rng] = len(order)
            order.append(rng)

    lines = []
    lines.append("//! GENERATED by tools/gen_unicode_props.py -- do not edit by hand.")
    lines.append("//! Unicode v17.0.0 property-escape range tables (sorted, disjoint).")
    lines.append("//! Source: test262 built-ins/RegExp/property-escapes/generated/*.js")
    lines.append("")
    lines.append("const R = [2]u21;")
    lines.append("")
    for i, rng in enumerate(order):
        parts = ", ".join(f".{{ 0x{lo:X}, 0x{hi:X} }}" for lo, hi in rng)
        if rng:
            lines.append(f"const P{i}: []const R = &.{{ {parts} }};")
        else:
            lines.append(f"const P{i}: []const R = &.{{}};")
    lines.append("")
    lines.append("/// Look up a Unicode property escape spelling (the exact text between")
    lines.append("/// `\\p{` and `}`) and return its sorted range table, or null if the")
    lines.append("/// spelling is not a valid/supported property (=> SyntaxError).")
    lines.append("pub fn lookup(name: []const u8) ?[]const R {")
    lines.append("    const eql = @import(\"std\").mem.eql;")
    # Sort spellings for stable output.
    for spelling in sorted(spelling_to_set.keys()):
        idx = unique[spelling_to_set[spelling]]
        # Zig string literal: spelling has only ASCII letters/digits/_/=; safe.
        esc = spelling.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    if (eql(u8, name, "{esc}")) return P{idx};')
    lines.append("    return null;")
    lines.append("}")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {OUT}: {len(spelling_to_set)} spellings, "
          f"{len(order)} unique tables, {sum(len(r) for r in order)} total ranges")

if __name__ == "__main__":
    main()
