#!/usr/bin/env python3
"""Generate src/runtime/builtins/unicode_casefold.zig.

RegExp Canonicalize under the `u`/`v` flag is the *simple* case folding of
CaseFolding.txt (the C and S status lines) — not the full folding and not
`toLowerCase`. CPython exposes only the full folding (`str.casefold()`, where
U+00DF folds to "ss"), so derive the simple mapping from it:

  * a full folding of exactly one code point IS the simple folding
    (U+017F LATIN SMALL LETTER LONG S folds to "s", U+212A KELVIN SIGN to "k");
  * a multi-code-point full folding means the character has no C/S line of its
    own, but it may still have one via `str.lower()` — U+1E9E LATIN CAPITAL
    LETTER SHARP S full-folds to "ss" while its simple folding is U+00DF.
    U+0130 and U+00DF lower to themselves (or to a sequence), so they stay put.

Run:  python3 tools/gen_unicode_casefold.py > src/runtime/builtins/unicode_casefold.zig
"""
import sys
import unicodedata

MAX_CP = 0x110000
SKIP = range(0xD800, 0xE000)  # surrogates are not Python str characters


# The three CaseFolding.txt S lines that neither `str.casefold()` nor
# `str.lower()` can reconstruct: both members of the pair full-fold to the same
# multi-code-point string and both already lowercase to themselves.
EXPLICIT_S = {
    0x1FD3: 0x0390,
    0x1FE3: 0x03B0,
    0xFB05: 0xFB06,
}


def simple_fold(cp):
    if cp in EXPLICIT_S:
        return EXPLICIT_S[cp]
    ch = chr(cp)
    folded = ch.casefold()
    if len(folded) == 1:
        return ord(folded)
    lowered = ch.lower()
    if len(lowered) == 1:
        return ord(lowered)
    return cp


def main():
    pairs = []
    for cp in range(MAX_CP):
        if cp in SKIP:
            continue
        f = simple_fold(cp)
        if f != cp:
            pairs.append((cp, f))

    out = sys.stdout
    out.write("// SPDX-License-Identifier: Apache-2.0\n")
    out.write("//! GENERATED by tools/gen_unicode_casefold.py -- do not edit.\n")
    out.write("//! Unicode %s simple case folding (CaseFolding.txt status C+S),\n"
              % unicodedata.unidata_version)
    out.write("//! the mapping RegExp Canonicalize uses under the `u`/`v` flag.\n")
    out.write("\n")
    out.write("pub const Fold = struct { cp: u21, fold: u21 };\n\n")
    out.write("/// Sorted by `cp` for binary search; identity mappings are omitted.\n")
    out.write("pub const folds: []const Fold = &.{\n")
    for cp, f in pairs:
        out.write("    .{ .cp = 0x%04X, .fold = 0x%04X },\n" % (cp, f))
    out.write("};\n\n")
    out.write("/// The same pairs sorted by `fold`, so every code point that folds to a\n")
    out.write("/// given value can be recovered as a contiguous run (`unfold`).\n")
    out.write("pub const by_fold: []const Fold = &.{\n")
    for cp, f in sorted(pairs, key=lambda p: (p[1], p[0])):
        out.write("    .{ .cp = 0x%04X, .fold = 0x%04X },\n" % (cp, f))
    out.write("};\n\n")
    out.write("""/// Simple case folding of `cp`, or `cp` itself when it has no mapping.
pub fn simpleFold(cp: u21) u21 {
    var lo: usize = 0;
    var hi: usize = folds.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = folds[mid];
        if (e.cp == cp) return e.fold;
        if (e.cp < cp) lo = mid + 1 else hi = mid;
    }
    return cp;
}

/// Every code point whose simple folding is `f`, excluding `f` itself. Used to
/// canonicalize a character class under `/iu`: the class may spell a member as
/// U+017F while the subject spells it "s" (or the other way round).
pub fn unfold(f: u21) []const Fold {
    var lo: usize = 0;
    var hi: usize = by_fold.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (by_fold[mid].fold < f) lo = mid + 1 else hi = mid;
    }
    var end = lo;
    while (end < by_fold.len and by_fold[end].fold == f) end += 1;
    return by_fold[lo..end];
}
""")


if __name__ == "__main__":
    main()
