#!/usr/bin/env python3
"""Generate src/runtime/builtins/unicode_case_tables.zig.

`String.prototype.toUpperCase`/`toLowerCase` are defined in terms of the
Unicode Default Case Conversion algorithm, which is the FULL mapping from
UnicodeData.txt plus the unconditional entries of SpecialCasing.txt — so a
single code point can expand to several (U+00DF LATIN SMALL LETTER SHARP S
uppercases to "SS", U+FB00 to "FF", ...). CPython's `str.upper()`/`str.lower()`
implement exactly that algorithm, so we harvest the tables from it rather than
re-parsing the UCD.

The one context-sensitive rule ECMAScript needs, Final_Sigma, is NOT baked in
here (a per-code-point table cannot express it); string_proto.zig applies it
using the Cased / Case_Ignorable property tables.
"""
import sys

MAX_CP = 0x110000
# Surrogates are not valid Python str characters; JS strings can hold lone
# surrogates, but they have no case mapping anyway.
SKIP = range(0xD800, 0xE000)


def collect(method):
    out = []
    for cp in range(MAX_CP):
        if cp in SKIP:
            continue
        ch = chr(cp)
        mapped = getattr(ch, method)()
        if mapped == ch:
            continue
        out.append((cp, [ord(c) for c in mapped]))
    return out


def emit(f, name, entries):
    f.write(f"pub const {name}: []const Entry = &.{{\n")
    for cp, mapped in entries:
        cps = ", ".join(f"0x{m:04X}" for m in mapped)
        f.write(f"    .{{ .cp = 0x{cp:04X}, .map = &.{{ {cps} }} }},\n")
    f.write("};\n\n")


def main():
    upper = collect("upper")
    lower = collect("lower")
    with open("src/runtime/builtins/unicode_case_tables.zig", "w") as f:
        import unicodedata
        f.write(
            "// Auto-generated by tools/gen_unicode_case.py from CPython's Unicode "
            f"{unicodedata.unidata_version} tables — do not edit by hand.\n"
            "//! Full (expanding) Default Case Conversion mappings for\n"
            "//! String.prototype.toUpperCase / toLowerCase. Entries are sorted by\n"
            "//! `cp`; code points absent from a table map to themselves.\n\n"
            "pub const Entry = struct { cp: u21, map: []const u21 };\n\n"
        )
        emit(f, "to_upper", upper)
        emit(f, "to_lower", lower)
        f.write(
            "/// Binary search for `cp`'s full case mapping; null means identity.\n"
            "pub fn lookup(table: []const Entry, cp: u21) ?[]const u21 {\n"
            "    var lo: usize = 0;\n"
            "    var hi: usize = table.len;\n"
            "    while (lo < hi) {\n"
            "        const mid = lo + (hi - lo) / 2;\n"
            "        const e = table[mid];\n"
            "        if (e.cp == cp) return e.map;\n"
            "        if (e.cp < cp) lo = mid + 1 else hi = mid;\n"
            "    }\n"
            "    return null;\n"
            "}\n"
        )
    print(f"upper: {len(upper)} entries, lower: {len(lower)} entries", file=sys.stderr)


main()
